name: flutter_core
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.3"
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter

  #  网络
  dio: ^5.4.0
  #  md5加密
  crypto: ^3.0.3
  #  序列化
  convert: ^3.1.1
  #  数据本地化
  shared_preferences: ^2.2.2
  #  图片缓存
  cached_network_image: ^3.3.1
  #  状态管理
  provider: ^6.1.1
  #  电话,短信,浏览器,其他app
  url_launcher: ^6.2.3
  #  日期格式化
  date_format: ^2.0.7
  #  吐司提示
  fluttertoast: ^8.2.4
  #  尺寸适配
  flutter_screenutil: ^5.9.0
  # 上下拉刷新
  pull_to_refresh_flutter3: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter_core.flutter_core
        pluginClass: FlutterCorePlugin
      ios:
        pluginClass: FlutterCorePlugin

